name: Satsails
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 1.0.0+28

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  go_router: ^14.3.0
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  local_auth: ^2.1.8
  hive: ^2.2.3
  webview_flutter: ^4.5.0
  webview_flutter_platform_interface: ^2.1.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
#  ai_barcode_scanner 3.4.3 for web compil
  fl_chart: ^0.66.2
  bip39: ^1.0.6
  flutter_riverpod: ^2.5.1
#  Need windows linux and web compils
  bdk_flutter: ^0.31.2-dev.2
  flutter_i18n: ^0.35.1
#  need windows linux ios and mac and web compils
  boltz_dart:
    git:
      url: https://github.com/SatoshiPortal/boltz-dart
      ref: trunk
  lwk_dart:
    git:
      url: https://github.com/SatoshiPortal/lwk-dart.git
      ref: trunk
  forex_currency_conversion: ^0.9.1
  icons_plus: ^5.0.0
  loading_animation_widget: ^1.2.1
  group_button: ^5.3.4
  liquid_pull_to_refresh: ^3.0.1
  action_slider: ^0.7.0
  hooks_riverpod: ^2.5.1
  fluttertoast: ^8.2.5
#  flutter_styled_toast: ^2.2.1 use to compil toas everywhere
  flutter_card_swiper: ^7.0.0
  calendar_date_picker2: ^0.5.6
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.2.6
  i18n_extension: ^12.0.1
  path_provider: ^2.1.4
  flutter_hooks: ^0.20.5
  decimal: ^3.0.2
  web_socket_channel: ^2.1.0
  permission_handler: ^9.0.1
  segmented_button_slide: ^1.0.4
  syncfusion_flutter_charts: ^27.1.48
  share_plus: ^10.0.0
  introduction_screen: ^3.1.14
  flutter_svg: ^2.0.10+1
  cpf_cnpj_validator: ^2.0.0
  intl: ^0.19.0
  coingecko_api: ^2.0.1
  flutter_image_slideshow: ^0.1.6
  crisp_chat: ^2.0.4
  currency_formatter: ^2.2.1
  flutter_local_notifications: ^17.2.3
  pusher_channels_flutter: ^2.2.1
  pusher_beams:
    git:
      url: https://github.com/sokhorninit/push-notifications-flutter
      path: packages/pusher_beams
      ref: master
  flutter_keyboard_done: ^1.0.1
dev_dependencies:
  build_runner: ^2.4.13
  flutter_dotenv: ^5.1.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17  
  flutter_lints: ^3.0.1
flutter:
  fonts:
    - family: lbtc_icon
      fonts:
        - asset: lib/assets/fonts/lbtc_icon.ttf
  uses-material-design: true
  assets:
    - lib/assets/app_icon.png
    - lib/assets/satsails.png
    - lib/assets/affiliates.png
    - lib/assets/GraficoAnalise.svg
    - lib/assets/satsails.svg
    - lib/assets/click.png
    - lib/assets/qr_code.png
    - lib/assets/support.png
    - lib/assets/wallet.png
    - lib/assets/frame.svg
    - lib/assets/depix.png
    - lib/assets/eurx.png
    - lib/assets/l-btc.png
    - lib/assets/tether.png
    - lib/assets/bip39_english.txt
    - .env

#compil incons to all envs
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "lib/assets/satsails.png"
  image_path_ios: "lib/assets/satsails_ios.png"

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/satsails.png"
  icon_background_color: "#000000"
  android: true
  ios: true
  web: false
  android_12:
    image: "lib/assets/satsails.png"
    icon_background_color: "#000000"
    color: "#000000"