name: Flutter Build APK and App Bundle

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_VERSION: '3.22.3'
      RUN_PIPELINE: 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        if: env.RUN_PIPELINE == 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Create google-services.json
        if: env.RUN_PIPELINE == 'true'
        run: |
          echo "$GOOGLE_SERVICES_JSON" > $GITHUB_WORKSPACE/android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Create key.properties
        if: env.RUN_PIPELINE == 'true'
        run: |
          echo "$KEY_PROPERTIES_FILE" > $GITHUB_WORKSPACE/android/key.properties
        env:
          KEY_PROPERTIES_FILE: ${{ secrets.KEY_PROPERTIES_FILE }}

      - name: Install dependencies
        if: env.RUN_PIPELINE == 'true'
        run: flutter pub get

      - name: Clean before build
        if: env.RUN_PIPELINE == 'true'
        run: flutter clean

      - name: Build APK
        if: env.RUN_PIPELINE == 'true'
        run: flutter build apk --release

      - name: Build App Bundle
        if: env.RUN_PIPELINE == 'true'
        run: flutter build appbundle --release

      - name: Upload APK
        if: env.RUN_PIPELINE == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle
        if: env.RUN_PIPELINE == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab
